# Generated by Django 4.2 on 2023-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chitietsp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
