# Generated by Django 4.2 on 2023-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_chitietsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cauhinhsp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
